// <auto-generated />
namespace wc_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FirstBlogPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstBlogPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202008032309113_FirstBlogPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
